# <font color='blue'>Understanding SQL Commands: DDL vs. DML</font>

SQL commands are divided into distinct categories based on what they actually do to the database. The two most important categories you will use daily are **DDL (Data Definition Language)** and **DML (Data Manipulation Language)**.



---

## 1. DDL: Data Definition Language (The "Architect")

DDL is used to define, alter, or destroy the **structure** and blueprint of your database. Think of DDL as dealing with the database containers (tables, views, indexes) rather than the actual data inside them.

* **Core Purpose:** Manages the schema/skeleton of the database.
* **Auto-Commit:** DDL commands usually save automatically and permanently right when you run them.

### Common DDL Commands:
* **`CREATE`**: Builds a brand-new table or database (e.g., `CREATE TABLE customers...`).
* **`ALTER`**: Modifies an *existing* structure, like adding a new column to a table (e.g., `ALTER TABLE customers ADD phone_number TEXT;`).
* **`DROP`**: Completely deletes a table and its structure from the database permanently.
* **`TRUNCATE`**: Removes all rows from a table, but leaves the empty container structure intact.

---

## 2. DML: Data Manipulation Language (The "Data Entry Clerk")

Once DDL has built the structure, DML is used to work with the **actual records** inside those structures. DML allows you to add, modify, retrieve, or delete the rows of information.

* **Core Purpose:** Manages the data content itself.
* **Control:** In production, DML changes can often be reviewed and rolled back (undone) before they are finalized.

### Common DML Commands:
* **`INSERT`**: Adds new rows of data (e.g., `INSERT INTO customers VALUES...`).
* **`SELECT`**: Retrieves and views data from the tables. *(Note: Some experts put SELECT in its own category called DQL, but it is traditionally grouped under data manipulation).*
* **`UPDATE`**: Modifies data that already exists inside a row.
* **`DELETE`**: Permanently removes rows from a table based on a condition.

---

### <font color='green'> These are sometimes referred to as **CRUD** operations.
- **C** : Create
- **R** : Read
- **U** : Update
- **D** : Delete (rows)

## ⚖️ Summary Comparison Chart

| Feature | DDL (Data Definition) | DML (Data Manipulation) |
| :--- | :--- | :--- |
| **What it affects** | The **Table Structure** (The Blueprint) | The **Row Data** (The Content) |
| **Key Operations** | `CREATE`, `ALTER`, `DROP`, `TRUNCATE` | `SELECT`, `INSERT`, `UPDATE`, `DELETE` |
| **Analogy** | Building or remodeling a filing cabinet. | Putting folders inside or pulling folders out of the cabinet. |

## <font color='blue'> Data Definition Language (DDL): The `CREATE TABLE` Statement </font>

The **`CREATE TABLE`** statement is the foundational command used in relational databases to establish a new, empty table. It defines the structural container—specifying the column names, the type of data each column can hold, and any rules (constraints) that the data must follow.



---

## 1. Core Syntax

The basic blueprint for writing a `CREATE TABLE` statement looks like this:

```sql
CREATE TABLE table_name (
    column1 data_type constraint,
    column2 data_type constraint,
    column3 data_type,
    ...
    PRIMARY KEY (column_name)
);

## 2. Key Components of the Statement

To build a table successfully, every column declaration requires two main pieces of information, and optionally a third:

* **Column Name:** A unique identifier for the column (e.g., `customer_id`, `total_amount`).
* **Data Type:** Tells the database what kind of value is allowed in that column:
  * `INT` / `INTEGER` (Whole numbers)
  * `VARCHAR(n)` / `TEXT` (Text strings of fixed or variable length)
  * `NUMERIC(p,s)` / `DECIMAL` (Exact fractional numbers like prices)
  * `TIMESTAMP` / `DATETIME` (Dates and times)
* **Constraints (Optional):** Rules applied to a column to protect data integrity:
  * `PRIMARY KEY`: Guarantees that every row has a completely unique, non-null identifier.
  * `NOT NULL`: Forces the column to always have a value (it cannot be left blank).
  * `UNIQUE`: Prevents duplicate entries within that specific column.
  * `DEFAULT value`: Automatically fills the column with a fallback value if none is provided during an insert.


**Example of <code>CREATE TABLE</code> statement based on the Module_1 transaction dataset**
```sql
CREATE TABLE transactions (
    transaction_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    timestamp DATETIME NOT NULL,
    product_name VARCHAR(100),
    total_amount NUMERIC(10, 2),
    payment_method VARCHAR(50) DEFAULT 'Cash'
);

### 🏋️ Practice Challenge: Build the `stadiums` Table

Write a complete `CREATE TABLE` statement using SQL. Below are the rules and requirements for the new table structure.

### Requirements:
1. **`stadium_id`**: A whole number that uniquely identifies each stadium. It cannot be empty and must serve as the **Primary Key**.
2. **`stadium_name`**: A text field (up to 100 characters) that is required (**NOT NULL**).
3. **`city`**: A text field (up to 50 characters) to store the location city.
4. **`capacity`**: An integer representing the total seating size of the stadium.
5. **`has_floodlights`**: A fixed text or boolean field that defaults to `'Yes'` if no value is given (**DEFAULT**).
6. **`average_rent`**: A decimal/numeric field to track the venue rental cost, allowing up to 10 total digits with 2 decimal places (e.g., `85000.50`).

---

In [8]:
# Create stadiums.csv
import csv

# Create and populate the CSV file automatically
data = [
    ["stadium_id", "stadium_name", "city", "capacity", "has_floodlights", "average_rent"],
    [1, "Melbourne Cricket Ground", "Melbourne", 100024, "Yes", 125000.00],
    [2, "Eden Gardens", "Kolkata", 68000, "Yes", 85000.50],
    [3, "Lord's Cricket Ground", "London", 31100, "No", 140000.00],
    [4, "Narendra Modi Stadium", "Ahmedabad", 132000, "Yes", 190000.00]
]

with open("stadiums.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerows(data)

print("stadiums.csv has been successfully created and populated!")

stadiums.csv has been successfully created and populated!

In [13]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')

conn.execute("""
CREATE TABLE stadiums
(
stadium_id INT PRIMARY KEY,
stadium_name VARCHAR(100) NOT NULL,
city VARCHAR(50),
capacity INT,
has_floodlights VARCHAR(4) DEFAULT 'Yes',
average_rent NUMERIC(10, 2)
);
""")

df_stadiums = pd.read_csv("stadiums.csv")
df_stadiums.to_sql('stadiums', conn, index=False, if_exists='append')

pd.read_sql_query("SELECT * FROM stadiums", conn)

,stadium_id,stadium_name,city,capacity,has_floodlights,average_rent
0,1,Melbourne Cricket Ground,Melbourne,100024,Yes,125000.0
1,2,Eden Gardens,Kolkata,68000,Yes,85000.5
2,3,Lord's Cricket Ground,London,31100,No,140000.0
3,4,Narendra Modi Stadium,Ahmedabad,132000,Yes,190000.0

## 🔄 The above example illustrates: File vs. Database

When you run your pipeline, Python treats your CSV file and your SQLite database as two completely separate worlds.

[Image diagram showing a one-way pipeline arrow moving from a CSV file into Pandas DataFrame memory, and then into an in-memory SQLite database container]

---

## What actually happened under the hood:

1. **`pd.read_csv("stadiums.csv")`**
   Pandas opens your CSV file, **reads a copy** of the data into your computer's temporary memory (RAM) as a DataFrame, and immediately closes the CSV file. The file on your hard drive stays exactly as it was.

2. **`CREATE TABLE stadiums...`**
   You built an empty, smart table container inside your active, in-memory **SQLite database (`conn`)**. This database lives purely in your computer's RAM.

3. **`to_sql(..., if_exists='append')`**
   Pandas takes that copy of the data from your RAM and pours it into the smart SQLite container.

---

## 💡 The Key Takeaway

You have **two distinct copies** of the data now:
* **The Original:** Your `stadiums.csv` file on your computer. It is just a static, dumb text file. It has no rules, no primary keys, and no database features.
* **The Active Database:** The `stadiums` table inside your SQLite `conn`. This is the smart, live table where your constraints (`PRIMARY KEY`, `DEFAULT`) are actively enforced.

If you use an `INSERT` or `UPDATE` command right now via `conn.execute()`, you are modifying the live **SQLite database in memory**, not the original CSV file.

In [14]:
# 1. Add a 5th stadium to our active SQLite database
conn.execute("""
INSERT INTO stadiums (stadium_id, stadium_name, city, capacity, average_rent)
VALUES (5, 'Lord''s Cricket Ground', 'London', 31100, 150000.00);
""")
conn.commit()

# 2. Query the LIVE DATABASE to see what it contains
print("--- DATA INSIDE YOUR SQLITE DATABASE ---")
print(pd.read_sql_query("SELECT * FROM stadiums", conn))

# 3. Read the ORIGINAL CSV file again to see what it contains
print("\n--- DATA INSIDE YOUR ORIGINAL CSV FILE ---")
print(pd.read_csv("stadiums.csv"))

--- DATA INSIDE YOUR SQLITE DATABASE ---
   stadium_id              stadium_name       city  capacity has_floodlights  \
0           1  Melbourne Cricket Ground  Melbourne    100024             Yes
1           2              Eden Gardens    Kolkata     68000             Yes
2           3     Lord's Cricket Ground     London     31100              No
3           4     Narendra Modi Stadium  Ahmedabad    132000             Yes
4           5     Lord's Cricket Ground     London     31100             Yes

   average_rent
0      125000.0
1       85000.5
2      140000.0
3      190000.0
4      150000.0

--- DATA INSIDE YOUR ORIGINAL CSV FILE ---
   stadium_id              stadium_name       city  capacity has_floodlights  \
0           1  Melbourne Cricket Ground  Melbourne    100024             Yes
1           2              Eden Gardens    Kolkata     68000             Yes
2           3     Lord's Cricket Ground     London     31100              No
3           4     Narendra Modi Stadium  Ahmedabad    132000             Yes

   average_rent
0      125000.0
1       85000.5
2      140000.0
3      190000.0

In [16]:
# Add 10 more entries to the stadiums database
conn.execute("""
INSERT INTO stadiums(stadium_id, stadium_name, city, capacity, has_floodlights, average_rent)
VALUES
    (6, 'The Oval', 'London', 27500, 'Yes', 95000.00),
    (7, 'Sydney Cricket Ground', 'Sydney', 48000, 'Yes', 110000.00),
    (8, 'Trent Bridge', 'Nottingham', 17500, NULL, 65000.00), -- Omitted/Null to test default fallback
    (9, 'Wankhede Stadium', 'Mumbai', 33108, 'Yes', 80000.00),
    (10, 'Adelaide Oval', 'Adelaide', 53583, 'Yes', 105000.00),
    (11, 'M. Chinnaswamy Stadium', 'Bengaluru', 40000, 'Yes', 75000.00),
    (12, 'The Gabba', 'Brisbane', 42000, 'Yes', 90000.00),
    (13, 'Newlands', 'Cape Town', 25000, 'No', 55000.00),
    (14, 'Old Trafford', 'Manchester', 26000, NULL, 70000.00), -- Another default fallback test
    (15, 'Eden Park', 'Auckland', 42000, 'Yes', 85000.00);
""")

conn.commit()

In [19]:
# Verify

pd.read_sql_query("""
SELECT *
FROM stadiums
""",
conn
                 )

,stadium_id,stadium_name,city,capacity,has_floodlights,average_rent
0,1,Melbourne Cricket Ground,Melbourne,100024,Yes,125000.0
1,2,Eden Gardens,Kolkata,68000,Yes,85000.5
2,3,Lord's Cricket Ground,London,31100,No,140000.0
3,4,Narendra Modi Stadium,Ahmedabad,132000,Yes,190000.0
4,5,Lord's Cricket Ground,London,31100,Yes,150000.0
5,6,The Oval,London,27500,Yes,95000.0
6,7,Sydney Cricket Ground,Sydney,48000,Yes,110000.0
7,8,Trent Bridge,Nottingham,17500,NaN,65000.0
8,9,Wankhede Stadium,Mumbai,33108,Yes,80000.0
9,10,Adelaide Oval,Adelaide,53583,Yes,105000.0
10,11,M. Chinnaswamy Stadium,Bengaluru,40000,Yes,75000.0
11,12,The Gabba,Brisbane,42000,Yes,90000.0
12,13,Newlands,Cape Town,25000,No,55000.0
13,14,Old Trafford,Manchester,26000,NaN,70000.0
14,15,Eden Park,Auckland,42000,Yes,85000.0

## <font color='blue'> Data Definition Language (DDL): The `ALTER TABLE` Statement</font>

The **`ALTER TABLE`** statement is used to modify the structure of an **existing** table in your database. Instead of dropping a table and recreating it from scratch (which would destroy all your existing data), `ALTER TABLE` lets you make structural adjustments on the fly.

[Image diagram showing the ALTER TABLE operation adding a new column to an existing database table structure]

---

## 1. What Can It Do?

While different database management systems (like PostgreSQL, MySQL, and SQLite) support different subsets of features, the three most common structural modifications are:

1. **Adding a new column** to an existing table.
2. **Deleting (dropping) a column** from an existing table.
3. **Modifying/Renaming** columns or the table itself.
4. **Add/remove** keys.
5. **Add/remove** constraints.

---

## 2. Core Syntax & Examples

Common usecases are:
- `ADD`
- `RENAME COLUMN`
- `DROP COLUMN`
- `DROP TABLE` $\rightarrow$ **Deletes the entire table**
- `TRUNCATE TABLE` $\rightarrow$ **Deletes the all data in the table but not the table.**

### <font color='blue'> A. Adding a Column (`ADD`)</font>
If your business requirements change and you need to start tracking a new piece of information (e.g., adding a `country` column to our `stadiums` table):

```sql
ALTER TABLE table_name
ADD column_name data_type;

In [26]:
# ADD a new column named 'country'
conn.execute("""
ALTER TABLE stadiums
ADD country VARCHAR(40);
""")

conn.commit()

OperationalError: duplicate column name: country

In [28]:
# Verify the columns
pd.read_sql_query(" SELECT * FROM stadiums LIMIT 10", conn)

,stadium_id,stadium_name,city,capacity,has_floodlights,average_rent,country
0,1,Melbourne Cricket Ground,Melbourne,100024,Yes,125000.0,None
1,2,Eden Gardens,Kolkata,68000,Yes,85000.5,None
2,3,Lord's Cricket Ground,London,31100,No,140000.0,None
3,4,Narendra Modi Stadium,Ahmedabad,132000,Yes,190000.0,None
4,5,Lord's Cricket Ground,London,31100,Yes,150000.0,None
5,6,The Oval,London,27500,Yes,95000.0,None
6,7,Sydney Cricket Ground,Sydney,48000,Yes,110000.0,None
7,8,Trent Bridge,Nottingham,17500,NaN,65000.0,None
8,9,Wankhede Stadium,Mumbai,33108,Yes,80000.0,None
9,10,Adelaide Oval,Adelaide,53583,Yes,105000.0,None

### <font color='blue'> B. Renaming a Column using `RENAME COLUMN`</font>

In [31]:
# RENAME the column 'city' to 'location_city'
conn.execute("""
ALTER TABLE stadiums
RENAME COLUMN city TO location_city;
""")

conn.commit()

In [33]:
# Verify
myquery = """
SELECT *
FROM stadiums
LIMIT 10;
"""
pd.read_sql_query(myquery, conn)

,stadium_id,stadium_name,location_city,capacity,has_floodlights,average_rent,country
0,1,Melbourne Cricket Ground,Melbourne,100024,Yes,125000.0,None
1,2,Eden Gardens,Kolkata,68000,Yes,85000.5,None
2,3,Lord's Cricket Ground,London,31100,No,140000.0,None
3,4,Narendra Modi Stadium,Ahmedabad,132000,Yes,190000.0,None
4,5,Lord's Cricket Ground,London,31100,Yes,150000.0,None
5,6,The Oval,London,27500,Yes,95000.0,None
6,7,Sydney Cricket Ground,Sydney,48000,Yes,110000.0,None
7,8,Trent Bridge,Nottingham,17500,NaN,65000.0,None
8,9,Wankhede Stadium,Mumbai,33108,Yes,80000.0,None
9,10,Adelaide Oval,Adelaide,53583,Yes,105000.0,None

### <font color='blue'> C. Drop the Column `country` using `DROP COLUMN`</font>

In [35]:
conn.execute("""
ALTER TABLE stadiums
DROP COLUMN country;
""")

conn.commit()

In [36]:
# Verify
myqueryc = """
SELECT *
FROM stadiums
LIMIT 10;
"""

pd.read_sql_query(myqueryc, conn)

,stadium_id,stadium_name,location_city,capacity,has_floodlights,average_rent
0,1,Melbourne Cricket Ground,Melbourne,100024,Yes,125000.0
1,2,Eden Gardens,Kolkata,68000,Yes,85000.5
2,3,Lord's Cricket Ground,London,31100,No,140000.0
3,4,Narendra Modi Stadium,Ahmedabad,132000,Yes,190000.0
4,5,Lord's Cricket Ground,London,31100,Yes,150000.0
5,6,The Oval,London,27500,Yes,95000.0
6,7,Sydney Cricket Ground,Sydney,48000,Yes,110000.0
7,8,Trent Bridge,Nottingham,17500,NaN,65000.0
8,9,Wankhede Stadium,Mumbai,33108,Yes,80000.0
9,10,Adelaide Oval,Adelaide,53583,Yes,105000.0