# <font color='blue'> Module 1: Selecting and Retrieving Data with SQL</font>
# <font color='grey'> Chapter 1: Introduction to SQL for Data Science</font>

## What are Data Models?

A **data model** is an abstract blueprint that defines how data is organized, stored, and managed within a database or information system. 

Think of a data model as an **architectural blueprint for data**. Just as a blueprint shows where walls, doors, and plumbing go before a house is built, a data model shows what data elements exist, how they are structured, and how they relate to one another before any code is written or databases are created.

---

### 1. The Three Levels of Data Modeling

When designing a system, data engineers don't just jump straight into writing database tables. They progress through three distinct layers of abstraction, moving from abstract business concepts to concrete technical code.



#### 1. Conceptual Data Model (The "What")
* **Purpose:** Built for business stakeholders to map out the big-picture scope of the system.
* **Focus:** It defines high-level concepts called **Entities** and how they connect, without any technical details.
* **Example:** *“A **Customer** can place multiple **Orders**, and each **Order** contains various **Products**.”*

#### 2. Logical Data Model (The "How")
* **Purpose:** Built for system architects and developers to structure the data properly.
* **Focus:** It specifies data types, attributes (columns), and strict operational rules, but remains independent of any specific database software.
* **Example:** *“The **Customer** entity has attributes like `CustomerID` (Integer), `Email` (Text), and `SignupDate` (Date).”*

#### 3. Physical Data Model (The "Implementation")
* **Purpose:** Built for Database Administrators (DBAs) to actually build the system.
* **Focus:** The actual technical database schema designed for a specific software platform (like PostgreSQL, MongoDB, or Oracle). It includes explicit data types, primary/foreign keys, indexes, and table constraints.
* **Example:** The exact SQL script containing commands like `CREATE TABLE customers (id INT PRIMARY KEY, email VARCHAR(255));`.

---

### 2. Common Types of Data Models

Depending on how data needs to be accessed, different mathematical shapes and structures—called **Data Model Types**—are used:

#### A. The Relational Model (SQL)
The most common model in the world. Data is strictly structured into **tables** made of rows and columns. Tables are linked to each other using common fields called "keys". 
* *Best for:* Financial transactions, ERP systems, and highly organized, predictable data.



#### B. Document Model (NoSQL)
Instead of rows and columns, data is stored in flexible, text-based files (usually **JSON documents**). Every record can have completely different fields.
* *Best for:* User profiles, content management systems, and fast-changing data.

#### C. Graph Model
Data is stored as **Nodes** (objects) and **Edges** (the explicit connections between them). 
* *Best for:* Mapping social networks (Facebook friends), recommendation engines (Netflix "people also watched"), and fraud detection.

---

### 3. Why Data Modeling Matters

Without a solid data model, a software system will eventually slow down, crash, or return bad information. Good data modeling provides:

* **Data Integrity:** It forces rules (e.g., *"You cannot create an Order for a Customer ID that does not exist"*).
* **Performance:** Well-modeled databases can search through billions of rows in milliseconds because the data paths are optimized.
* **Cost Savings:** It is significantly cheaper to fix a structural mistake on a conceptual design board than it is to rewrite millions of lines of active database code later.

## Understanding Relational and Transactional Models

While people often hear the terms **Relational** and **Transactional** used together in database discussions, they actually describe two entirely different aspects of data management:

* **Relational** describes **how data is shaped and organized** (the structural model).
* **Transactional** describes **how data is processed and updated** (the behavioral model).

Here is a breakdown of how each model works, how they intersect, and how they differ from analytical structures.

---

## 1. The Relational Model (Data Structure)

Invented by Edgar F. Codd at IBM in 1970, the **Relational Model** organizes data into highly structured, two-dimensional tables consisting of **rows** (tuples) and **columns** (attributes). 

### Key Characteristics:
* **Tables (Relations):** Every table represents a specific entity type (e.g., `Customers`, `Products`, `Orders`).
* **Keys:** Tables are linked to one another using unique identifiers. 
  * **Primary Key:** A column that uniquely identifies a row in its own table (e.g., `CustomerID`).
  * **Foreign Key:** A column in one table that references the Primary Key of another table, creating a relational link.
* **Schema Enforcement:** The structure is strict. You cannot add a row with missing mandatory columns or mismatched data types.



### Example Structure:
If a customer buys a product, the database doesn't write all of the customer's personal details directly into the order receipt. Instead, it references their ID:

```text
[ Customers Table ]                 [ Orders Table ]
• CustomerID (PK): 101   <======    • OrderID: 5001
• Name: Alice Smith            \\   • CustomerID (FK): 101
• Email: alice@email.com        \\= • TotalAmount: $45.00

## 2. The Transactional Model (Data Processing)

The **Transactional Model** focuses on ensuring data integrity when data is being written, updated, or deleted. It is built around the concept of a **Transaction**: a sequence of one or more database operations treated as a **single, indivisible unit of work**.

In a transactional database, either **everything succeeds, or everything fails**. There is no middle ground.

---

### The ACID Guarantees
To safely process data, transactional models must strictly adhere to the **ACID** framework:



* **Atomicity (All-or-Nothing):** If an operation contains 5 steps and step 4 fails, the entire transaction is aborted, and the database rolls back to its original state as if nothing happened.
* **Consistency:** A transaction can only take the database from one valid state to another, maintaining all predefined schema rules and constraints.
* **Isolation:** If multiple users are updating the database at the exact same millisecond, their transactions are isolated from one another so they don't corrupt each other's data mid-process.
* **Durability:** Once a transaction is successfully completed ("committed"), the changes are permanently saved to disk and will not be lost, even if the server immediately loses power.

---

### Classic Example: A Bank Transfer
Imagine you transfer \$100 from your Checking Account to your Savings Account. This requires two distinct operations:

* **Step 1:** Subtract \$100 from Checking.
* **Step 2:** Add \$100 to Savings.

> 💡 **Why the Transactional Model matters:** If the server crashes or the network drops *after* Step 1 but *before* Step 2, \$100 would vanish into thin air. A transactional database prevents this by rolling back Step 1 if Step 2 cannot be completed.

## <font color='blue'>What are ER Diagrams?</font>

An **ER Diagram** (Entity-Relationship Diagram) is a visual blueprint used in software engineering and data design to map out the structure of a database. It shows the "things" or objects stored in the system (**Entities**), the characteristics that define them (**Attributes**), and how they interact with one another (**Relationships**). 

Think of it as a logical map of your data before you write any SQL code or create physical database tables.

---

## ER Diagram Notation

**ER Diagram Notation**, compares how different design standards visually represent cardinalities (the numerical constraints of relationships: One-to-One, One-to-Many, or Many-to-Many). 



It breaks these concepts down across three popular industry formats:
1. **Chen Notation:** An older, highly conceptual style using diamonds for relationships and text letters ($1, M, N$) to indicate counts.
2. **Crow's Foot Notation:** The most common standard used in modern relational database design, using lines, dashes, and fork-like "crow's feet" symbols.
3. **UML Class Diagram Notation:** Used extensively in object-oriented programming and software architecture, utilizing decimals and asterisks ($1..1$, $1..*$) to indicate ranges.

Here is a detailed breakdown of the three structural business rules shown in the image:

---

### 1. One-to-Many Relationship ($1:M$)

* **The Business Rule:** A single `PAINTER` can paint many `PAINTINGS`, but each individual `PAINTING` can only be painted by exactly one `PAINTER`.
* **How it's represented:**
  * **Chen Notation:** Uses a `1` next to the Painter block and an `M` (Many) next to the Painting block, split by a diamond labeled "paints".
  * **Crow's Foot Notation:** Shows two parallel vertical bars ($||$) next to Painter (meaning "exactly one") and a split "crow's foot" fork ($<$) next to Painting (meaning "many").
  * **UML Notation:** Uses `1..1` (one and only one) on the Painter side and `1..*` (one to many) on the Painting side.

---

### 2. Many-to-Many Relationship ($M:N$)

* **The Business Rule:** An `EMPLOYEE` can learn many different `SKILLS`, and a single `SKILL` can be learned by many different `EMPLOYEES`.
* **How it's represented:**
  * **Chen Notation:** Uses an `M` on one side and an `N` on the other to represent two distinct "many" boundaries.
  * **Crow's Foot Notation:** Both ends of the relationship line terminate in a split "crow's foot" fork ($<$), showing multiplicity on both sides.
  * **UML Notation:** Uses `1..*` on both ends, indicating that any entry on either side can associate with one or more entries on the other.

---

### 3. One-to-One Relationship ($1:1$)

* **The Business Rule:** An `EMPLOYEE` manages exactly one `STORE`, and each `STORE` is managed by exactly one `EMPLOYEE`.
* **How it's represented:**
  * **Chen Notation:** Uses a literal `1` on both sides of the relationship diamond labeled "manages".
  * **Crow's Foot Notation:** Both ends of the connecting line feature the double parallel vertical bars ($||$), enforcing a strict limitation that neither side can exceed a single connection.
  * **UML Notation:** Explicitly uses `1..1` on both ends to denote a strict, single-instance pairing.

## <font color='blue'> Retrieving Data Using the `SELECT` Statement </font>

In SQL (Structured Query Language), the **`SELECT` statement** is the primary tool used to fetch and retrieve data from a database. 

Think of a database table like a massive spreadsheet. The `SELECT` statement allows you to pull out specific columns (vertical slices) and specific rows (horizontal slices) that meet your exact criteria.

---

### 1. The Standard SQL Query Order

When writing a query, SQL expects commands to be written in a very specific grammatical order. This is known as the **syntax order**:



Here is the most common foundational structure:

```sql
SELECT column1, column2
FROM table_name
WHERE condition
ORDER BY column1 ASC;

### <font color='blue'> Practice Exercises </font>
### Practicing SQL with Your 1,000-Row Dataset

Since you want to use pure SQL to practice your data retrieval, we need a way to run SQL queries inside your Python Jupyter Notebook without needing to install complex database servers like PostgreSQL or MySQL.

The easiest way to do this is to use **SQLite** (a lightweight database engine built directly into Python) along with a library called `pandasql`, which allows you to run standard SQL statements directly against a Pandas DataFrame.

---

**Setting Up Your Environment**

First, you need to install `pandasql` if you haven't already. Run this command in a blank cell to install it via pip:

```python
!pip install pandasql

In [1]:
# Generate dataset 'practice_transactions.csv'
import pandas as pd
import random
from datetime import datetime, timedelta

# 1. Set seed for reproducibility
random.seed(42)

# 2. Define our reference/relational template data
products = {
    "Laptop": {"category": "Electronics", "price": 999.99},
    "Smartphone": {"category": "Electronics", "price": 599.99},
    "Headphones": {"category": "Electronics", "price": 149.99},
    "Coffee Maker": {"category": "Appliances", "price": 89.99},
    "Blender": {"category": "Appliances", "price": 45.00},
    "Running Shoes": {"category": "Apparel", "price": 120.00},
    "T-Shirt": {"category": "Apparel", "price": 25.00},
    "Backpack": {"category": "Apparel", "price": 49.99},
    "Desk Chair": {"category": "Furniture", "price": 180.00},
    "Book": {"category": "Media", "price": 14.99}
}

product_list = list(products.keys())
payment_methods = ["Credit Card", "PayPal", "Debit Card", "Apple Pay"]

# 3. Generate 1000 transactional entries
data = []
start_date = datetime(2026, 1, 1)

for i in range(1, 1001):
    # Relational Entity Keys
    transaction_id = 5000 + i
    customer_id = random.randint(100, 250) # 150 unique customers
    
    # Transactional attributes
    product_name = random.choice(product_list)
    category = products[product_name]["category"]
    unit_price = products[product_name]["price"]
    
    quantity = random.choices([1, 2, 3, 4], weights=[70, 20, 8, 2])[0]
    total_amount = round(unit_price * quantity, 2)
    
    # Generate incremental timestamps across the year
    timestamp = start_date + timedelta(minutes=random.randint(1, 200000))
    payment = random.choice(payment_methods)
    
    data.append([
        transaction_id, customer_id, timestamp.strftime("%Y-%m-%d %H:%M:%S"),
        product_name, category, unit_price, quantity, total_amount, payment
    ])

# 4. Convert to DataFrame
columns = [
    "transaction_id", "customer_id", "timestamp", 
    "product_name", "category", "unit_price", 
    "quantity", "total_amount", "payment_method"
]
df = pd.DataFrame(data, columns=columns)

# 5. Save to CSV for external SQL/Excel practice
df.to_csv("practice_transactions.csv", index=False)

# Display the first 5 rows of your 1000-row dataset
print(f"Successfully generated {len(df)} rows and saved to 'practice_transactions.csv'!")
df.head()

Successfully generated 1000 rows and saved to 'practice_transactions.csv'!

,transaction_id,customer_id,timestamp,product_name,category,unit_price,quantity,total_amount,payment_method
0,5001,128,2026-02-14 13:57:00,Laptop,Electronics,999.99,2,1999.98,PayPal
1,5002,135,2026-04-10 06:45:00,Smartphone,Electronics,599.99,1,599.99,Credit Card
2,5003,208,2026-02-09 19:15:00,Laptop,Electronics,999.99,1,999.99,PayPal
3,5004,229,2026-02-06 04:45:00,Book,Media,14.99,1,14.99,Apple Pay
4,5005,156,2026-01-02 04:24:00,Backpack,Apparel,49.99,1,49.99,PayPal

In [2]:
# Import the generated dataset into the notebook environment
import pandas as pd
from pandasql import sqldf

# Load the practice dataset
df = pd.read_csv("practice_transactions.csv")

# Create a helper function for running SQL queries
def run_sql(query):
    return sqldf(query, globals())

print("SQL Environment is ready!")

SQL Environment is ready!

In [5]:
# Select specific columns, select specific entries satisfying a certain condition
# and then order the results in descending order (ASC for ascending and DESC for descending order)
query1 = """
SELECT customer_id, product_name
FROM df
WHERE unit_price > 100
ORDER BY unit_price DESC;
"""

run_sql(query1)

     customer_id   product_name
0            128         Laptop
1            208         Laptop
2            167         Laptop
3            183         Laptop
4            241         Laptop
..           ...            ...
502          228  Running Shoes
503          183  Running Shoes
504          195  Running Shoes
505          172  Running Shoes
506          141  Running Shoes

[507 rows x 2 columns]

In [7]:
# All high-value transactions where a customer purchased items from the Electronics category and spent more than $500.
query2 = """
SELECT customer_id,
       product_name,
       unit_price,
       total_amount
FROM df
WHERE category='Electronics' AND total_amount > 500
ORDER BY total_amount DESC;
"""

run_sql(query2)

     customer_id product_name  unit_price  total_amount
0            145       Laptop      999.99       3999.96
1            235       Laptop      999.99       3999.96
2            133       Laptop      999.99       3999.96
3            222       Laptop      999.99       2999.97
4            131       Laptop      999.99       2999.97
..           ...          ...         ...           ...
200          219   Headphones      149.99        599.96
201          170   Headphones      149.99        599.96
202          124   Headphones      149.99        599.96
203          177   Headphones      149.99        599.96
204          225   Headphones      149.99        599.96

[205 rows x 4 columns]

In [10]:
# all transactions where someone bought a Laptop, and sort them so that 
# the largest transaction amounts appear right at the top (DESC stands for descending order).

query3 = """
SELECT transaction_id, 
       customer_id, 
       unit_price, 
       quantity, 
       total_amount
FROM df
WHERE product_name="Laptop" AND unit_price > 100
ORDER BY total_amount DESC
"""

run_sql(query3)

    transaction_id  customer_id  unit_price  quantity  total_amount
0             5423          145      999.99         4       3999.96
1             5609          235      999.99         4       3999.96
2             5800          133      999.99         4       3999.96
3             5111          222      999.99         3       2999.97
4             5179          131      999.99         3       2999.97
..             ...          ...         ...       ...           ...
83            5878          110      999.99         1        999.99
84            5914          205      999.99         1        999.99
85            5947          143      999.99         1        999.99
86            5972          102      999.99         1        999.99
87            5980          221      999.99         1        999.99

[88 rows x 5 columns]

In [11]:
df.head()

,transaction_id,customer_id,timestamp,product_name,category,unit_price,quantity,total_amount,payment_method
0,5001,128,2026-02-14 13:57:00,Laptop,Electronics,999.99,2,1999.98,PayPal
1,5002,135,2026-04-10 06:45:00,Smartphone,Electronics,599.99,1,599.99,Credit Card
2,5003,208,2026-02-09 19:15:00,Laptop,Electronics,999.99,1,999.99,PayPal
3,5004,229,2026-02-06 04:45:00,Book,Media,14.99,1,14.99,Apple Pay
4,5005,156,2026-01-02 04:24:00,Backpack,Apparel,49.99,1,49.99,PayPal

In [12]:
# Select the transaction_id, product_name, and payment_method from the table df, 
# but only for transactions where the payment_method is exactly 'PayPal'

query4 = """
SELECT transaction_id,
       product_name,
       payment_method
FROM df
WHERE payment_method="PayPal"
ORDER BY total_amount ASC
"""

run_sql(query4)

     transaction_id product_name payment_method
0              5033         Book         PayPal
1              5056         Book         PayPal
2              5127         Book         PayPal
3              5169         Book         PayPal
4              5304         Book         PayPal
..              ...          ...            ...
233            5571       Laptop         PayPal
234            5179       Laptop         PayPal
235            5504       Laptop         PayPal
236            5532       Laptop         PayPal
237            5609       Laptop         PayPal

[238 rows x 3 columns]